---
# tasks file for install_nginx

    - name: get app_data.xml
      raw: "system_profiler SPInstallHistoryDataType -xml > /tmp/app_data.xml"
      args:
        executable: /bin/bash

    - name: post app_data.xml to flask
      raw: "curl -X POST -d @/tmp/app_data.xml  -H 'Accept: application/xml'  -H 'Content-Type: application/xml' http://172.22.214.66:5000/api/applications?serialnumber=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')"
      args:
        executable: /bin/bash
